### ISSUE TITLE
CosineSimilarity extension method not found.

### ISSUE THREAD

**Issue by amitchaudhary** [filipw/strathweb-samples-azureopenai#1]
var similarity = vector.CosineSimilarity(baselineVector);

Even after adding the package Microsoft.SemanticKernel

**Comment by filipw** [comment]
They were removed from SemanticKernel in version 1.0.0.
Instead, you can use the vector operations from [System.Numerics.Tensors](https://www.nuget.org/packages/System.Numerics.Tensors). 

See this commit for reference https://github.com/filipw/Strathweb.Samples.AzureOpenAI/commit/eba9c43069acd1182e2d2fb4b741f0ebd7163171
